//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENT()
        {
            this.COMMANDE = new HashSet<COMMANDE>();
        }
    
        public decimal IDCLIENT { get; set; }
        public string NOMCLIENT { get; set; }
        public string PRENOMCLIENT { get; set; }
        public string COURIEL { get; set; }
        public string MOTDEPASSE { get; set; }
        public string TELEPHONECLIENT { get; set; }
        public string NOCIVIQUE { get; set; }
        public string NOAPP { get; set; }
        public string NOMRUE { get; set; }
        public string VILLE { get; set; }
        public string PROVINCE { get; set; }
        public string PAYS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMANDE> COMMANDE { get; set; }
    }
}
