//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURE
    {
        public decimal IDFACTURE { get; set; }
        public decimal NOCOMMANDE { get; set; }
        public Nullable<decimal> PRIXHT { get; set; }
        public Nullable<decimal> PRIXTTC { get; set; }
        public Nullable<System.DateTime> DATEFACTURATION { get; set; }
    
        public virtual COMMANDE COMMANDE { get; set; }
    }
}
