//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIGNE_COMMANDE
    {
        public decimal NOCOMMANDE { get; set; }
        public decimal IDPRODUIT { get; set; }
        public Nullable<decimal> QUANTITE { get; set; }
    
        public virtual PRODUIT PRODUIT { get; set; }
    }
}
